//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIM_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATIM_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24px_VisualEditor___Icon___add_reference_svg1 {
            get {
                object obj = ResourceManager.GetObject("24px-VisualEditor_-_Icon_-_add-reference.svg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Apply_16x16 {
            get {
                object obj = ResourceManager.GetObject("Apply_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #ATIM Communication Settings
        ///#Please don&apos;t change me, if you don&apos;t know how I work
        ///
        ///Rth-Rack(Serial)
        ///Rth-Rack_Port=COM7
        ///Rth-Rack_BaudRate=57600
        ///Rth-Rack_DataBits=8
        ///Rth-Rack_StopBits=One
        ///Rth-Rack_Parity=None
        ///Rth-Rack_Timeout=500
        ///
        ///TEC-Meerstetter(Serial)
        ///TEC-Meerstetter_Port=COM12
        ///TEC-Meerstetter_BaudRate=57600
        ///TEC-Meerstetter_DataBits=8
        ///TEC-Meerstetter_StopBits=One
        ///TEC-Meerstetter_Parity=None
        ///TEC-Meerstetter_Timeout=500
        ///
        ///PowerSupply-HMP4040(Serial)
        ///PowerSupply-HMP4040_Port=COM3
        ///PowerSupp [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ATIM_Communication_Settings {
            get {
                return ResourceManager.GetString("ATIM_Communication_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Auto_Connect {
            get {
                object obj = ResourceManager.GetObject("Auto_Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Auto_Connect_transparent {
            get {
                object obj = ResourceManager.GetObject("Auto_Connect_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Auto_Connect1 {
            get {
                object obj = ResourceManager.GetObject("Auto_Connect1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_transparent {
            get {
                object obj = ResourceManager.GetObject("Cancel_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_transparent1 {
            get {
                object obj = ResourceManager.GetObject("Cancel_transparent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("Delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kFaktor_Symbol_transparent {
            get {
                object obj = ResourceManager.GetObject("kFaktor_Symbol_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kFaktor_Symbol_transparent1 {
            get {
                object obj = ResourceManager.GetObject("kFaktor_Symbol_transparent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #Predifined Positions
        ///#Please don&apos;t change me, if you don&apos;t know how I work
        ///#Syntax: [name]: x=[x in mm] y=[y in mm] z=[z in mm] a=[angle]
        ///
        ///Reference position: x=0 y=0 z=0 a=0
        ///Parking position: x=195 y=-178 z=0 a=0
        ///Start MiniMatrix: x=187.375 y=-274 z=0 a=0
        ///Start Neo 36: x=195 y=-298 z=0 a=0
        ///Start MOSFET: x=188.75 y=-283.5 z=0 a=0 ähnelt.
        /// </summary>
        internal static string Predefined_Positions {
            get {
                return ResourceManager.GetString("Predefined_Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReferenceDrive {
            get {
                object obj = ResourceManager.GetObject("ReferenceDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [SRV_PAR]
        ///
        ///labelM_PAR_VER_HW_SERNR=1726
        ///label_uc_Version=3
        ///label_PAR_VER_HW_SERNR=1726
        ///label_PAR_TEC1_MODE=Temperature Controller
        ///label_PAR_TEC2_MODE=Temperature Controller
        ///label_PAR_TEC_EN1=Static ON
        ///label_PAR_TEC_EN2=Static ON
        ///label_PAR_TEC1_Set_I=1
        ///label_PAR_TEC1_Set_U=10
        ///label_PAR_TEC2_Set_I=1
        ///label_PAR_TEC2_Set_U=10
        ///label_PAR_TEC1_LIMIT_I=8
        ///label_PAR_TEC1_LIMIT_U=15.7
        ///label_PAR_TEC2_LIMIT_I=8
        ///label_PAR_TEC2_LIMIT_U=15.7
        ///label_PAR_TEC1_ERRORLIMIT_I=9
        ///label_PAR_TEC1_ERRORLIMIT_U=17
        ///lab [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string TEC {
            get {
                return ResourceManager.GetString("TEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thi_big {
            get {
                object obj = ResourceManager.GetObject("thi_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thi_big1 {
            get {
                object obj = ResourceManager.GetObject("thi_big1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap U_I_Symbol_transparent {
            get {
                object obj = ResourceManager.GetObject("U_I_Symbol_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap U_I_Symbol_transparent1 {
            get {
                object obj = ResourceManager.GetObject("U_I_Symbol_transparent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning_16x16 {
            get {
                object obj = ResourceManager.GetObject("Warning_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zth_Symbol_transparent {
            get {
                object obj = ResourceManager.GetObject("Zth_Symbol_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zth_Symbol_transparent1 {
            get {
                object obj = ResourceManager.GetObject("Zth_Symbol_transparent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
